# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.


main:
  - name: About
    url: ''
    weight: 10

  - name: CV
    url: 'cv'
    weight: 30


  - name: Research
    url: 'research'
    weight: 50


#  - name: Work
#    url: 'work'
#    weight: 70


  - name: Publications
    url: 'publications'
    weight: 90


  - name: Activities
    url: 'activities'
    weight: 110


  - name: Gallery
    url: 'gallery'
    weight: 130



# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: Curriculum Vitae
#    url: uploads/leonelli_mauro.pdf
#    weight: 50
